version: "1.27"
image: nginx:1.27-alpine
description: Nginx 1.27
port: 80
protocol: http
volumes:
  - /usr/share/nginx/html
  - /etc/nginx/conf.d
healthcheck:
  test:
    - CMD-SHELL
    - wget --no-verbose --tries=1 --spider http://localhost/ || exit 1
  interval: 10s
  timeout: 5s
  retries: 3
  start: 5s
resources:
  memory_min: 64m
  memory_max: 256m
  cpu_min: "0.1"
  cpu_max: "0.5"
