name: Elasticsearch
description: Distributed search and analytics engine
category: search
icon: "\U0001F50D"
tags:
  - search
  - analytics
  - elasticsearch
links:
  homepage: https://www.elastic.co/elasticsearch
  documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html
  repository: https://github.com/elastic/elasticsearch
available_versions:
  - "8.15"
  - "8.11"
latest_version: "8.15"
