name: RabbitMQ
description: Message broker with management UI
category: queue
icon: "\U0001F430"
tags:
  - queue
  - message-broker
  - amqp
links:
  homepage: https://www.rabbitmq.com
  documentation: https://www.rabbitmq.com/documentation.html
  repository: https://github.com/rabbitmq/rabbitmq-server
available_versions:
  - "4.0"
  - "3.12"
latest_version: "4.0"
