version: "1.52"
image: jaegertracing/all-in-one:1.52
description: Jaeger all-in-one 1.52
port: 16686
admin_port: 14268
protocol: http
environment:
  COLLECTOR_OTLP_ENABLED: "true"
healthcheck:
  test:
    - CMD-SHELL
    - wget --spider -q http://localhost:14269/ || exit 1
  interval: 10s
  timeout: 5s
  retries: 5
  start: 10s
resources:
  memory_min: 256m
  memory_max: 1g
  cpu_min: "0.25"
  cpu_max: "1.0"
